---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```


```{r}
levels(student$身高級距)[c(1:3)]<-c("(0.160]")
levels(student$身高級距)
```

```{r}
library(googlesheets)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
dim(classSurvey)
ncol(classSurvey)
```

```{r}
class(classSurvey$學號)
classSurvey$學號 <- as.character(classSurvey$學號)
library(stringr)
classSurvey$年級 <- str_sub(classSurvey$學號,2,4)
classSurvey$年級 <- as.factor(classSurvey$年級)
levels(classSurvey$年級) <- c("大四及以上","大三","大二","大一")
```

```{r}
freshIndicator<-(classSurvey$年級=="大一")
freshactivity <-
classSurvey$本學期目前已參加之課外活動[freshIndicator]
library(stringr)
str_split_fixed(freshactivity,",",n=5)-> aa
str_c(aa) -> bb
table(bb)
```

```{r}
bb
```

